name: sjis
version: 0.2.0
description: Converter for SJIS(shift_jis)
author: Yuki Awano <y.a.unix@gmail.com>
homepage: http://www.yaunix.com/
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  test: 1.6.3
